### ISSUE TITLE
Failure to deploy oVirt node with security profile (PCI-DSS)

### ISSUE THREAD

**Issue by gpavinteractiv** [oVirt/ovirt-node-ng-image#113]
As reported on ovirt users mailing list: 

I tried with el8 & el9 oVirt Node 4.5.4 isos, 
But in both cases, the installation failed when selecting the PCI-DSS security profile. Please see screenshots attached

According to 4.5.0 release note this is a supported feature  :

> _BZ 2030226 [RFE] oVirt hypervisors should support running on hosts with the PCI-DSS security profile applied
> The oVirt Hypervisor is now capable of running on machine with PCI-DSS security profile._

https://bugzilla.redhat.com/show_bug.cgi?id=2030226

As the RFE says that deployment works, I guess this is a regression somewhere between 4.5.0 & 4.5.4

On the mailing list, @sandrobonazzola answered :

> In the screenshot I see ssg-onn4-ds being selected, I would have expected it to be ssg-onn45-ds.xml as that's the one being created in https://github.com/oVirt/ovirt-node-ng-image. 
> This one should be an easy fix, just changing the name of the file to match what's expected by anaconda.

![Screenshot from 2023-04-03 15-41-15](https://user-images.githubusercontent.com/26144994/230310990-3df33156-3dda-48ed-bb98-d996a6e833ba.png)
![Screenshot from 2023-04-03 15-56-03](https://user-images.githubusercontent.com/26144994/230310996-7b8dd02b-0bdc-46e5-8d14-d2ff10f9cee3.png)
![Screenshot from 2023-04-03 15-56-18](https://user-images.githubusercontent.com/26144994/230311001-4bfbbbe0-2656-45ca-8cae-9139041bcd1c.png)
![Screenshot from 2023-04-03 15-56-31](https://user-images.githubusercontent.com/26144994/230311004-5402f7fe-b2d1-4675-a65f-90192aa91a20.png)
![Screenshot from 2023-04-03 15-56-55](https://user-images.githubusercontent.com/26144994/230311008-4b73e98e-7881-443c-ae23-2d31954fbdbf.png)
![Screenshot from 2023-04-03 15-57-11](https://user-images.githubusercontent.com/26144994/230311013-2872f052-871a-45f3-8805-4e9ca4b1b2ff.png)

**Comment by michalskrivanek** [comment]
"BZ 2030226 [RFE] oVirt hypervisors should ..." is probably just an automatic translation, you can see in the bug it was a RHV feature. We do not test this upstream in oVirt really, mostly because it's hard to keep up with the profile changes. It may work, I don't mind merging a patch if you post one and confirm it works.

**Comment by gpavinteractiv** [comment]
I don't have the know how to build an image with theses change in order to test them.
Could the build be done on oVirt infra, if such thing is possible, and I'll happily test and report ?

**Comment by michalskrivanek** [comment]
unfortunately not. for this project the automation is too tied with actual release. But it shouldnt' be that difficult to run locally, just prepare host as https://github.com/oVirt/ovirt-node-ng-image/blob/master/.github/workflows/build.yml#L40 and run priviledged container from https://github.com/oVirt/ovirt-node-ng-image/blob/master/.github/workflows/build.yml#L57 with the script and few variables like https://github.com/oVirt/ovirt-node-ng-image/blob/master/.github/workflows/build.yml#L66

**Comment by gpavinteractiv** [comment]
@michalskrivanek 
I'm totally unsure of the individual steps to build the iso.

On a clean centos stream 9, could you provide the exact command flow that will result in creating the container with the proper variables you mentioned and then run build.sh?

**Comment by michalskrivanek** [comment]
i dont' have it at hand, but really just copying from the workflow code it should be
          mkdir -p /host/modules
          mount --bind /lib/modules/$(uname -r) /host/modules
          podman run -it --privileged -v /host/modules:/host/modules quay.io/ovirt/buildcontainer:el9stream 
and then inside just check out the repo with your PR and run
          export SUPERMIN_MODULES=/host/modules
          export SUPERMIN_KERNEL=/host/modules/vmlinuz
          build.sh

**Comment by gpavinteractiv** [comment]
Thank!
We have build the centos 9 iso with the aforementioned patch  : 

Change the name of the file to match what's expected by anaconda. From :
```ln -sf/usr/share/xml/scap/ssg/content/{ssg-rhel9,ssg-onn45}-ds.xml```
To :
```ln -sf /usr/share/xml/scap/ssg/content/{ssg-rhel9,ssg-onn4}-ds.xml```

Please note that we kept linking from ssg-rhel9-ds.xml, as originally. 
However, there is also a ssg-cs9-ds.xml in the same folder.

- Do you know if applying the rhel9 rules to a centos is valid ?

- We got an error when starting the installtaion : 
![Screenshot from 2023-04-19 22-32-18](https://user-images.githubusercontent.com/26144994/235842460-88e4c77b-a225-4cce-8934-44ed274d4992.png)

The host has been provisioned and joined to the oVirt Cluster. It seems to be working properly.
- Do you know how can we check that the PCI-DSS profile has been correctly applied?

**Comment by sandrobonazzola** [comment]
Please use the cs9 one as the OVAL tuple isn't matching between cs9 and rhel9.

Once deployed, you can check it with:

`sudo oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_pci-dss --report /tmp/report.html /usr/share/xml/scap/ssg/content/ssg-cs9-ds.xml ` and look at the report.

**Comment by sandrobonazzola** [comment]
Should be fixed by #115
