### ISSUE TITLE
Missing el9 builds on GitHub actions

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-node-ng-image#3]
The existing GitHub action is building only el8. We need el9 as well.

**Comment by sandrobonazzola** [comment]
cc @michalskrivanek as he prepared the el8 job

**Comment by ovirt-infra** [comment]
we need a GH runner first.

**Comment by michalskrivanek** [comment]
fixed by #9 
both el8 and el9 rpms and isos are in https://resources.ovirt.org/repos/ovirt/github-ci/ovirt-node-ng-image/
