### ISSUE TITLE
imgbased dependency causes upgrade issues

### ISSUE THREAD

**Issue by dupondje** [oVirt/ovirt-node-ng-image#51]
**Describe the bug**
Due to commit https://github.com/oVirt/ovirt-node-ng-image/commit/14f48fdf0bb1501b152b92d6b48c83b2dae03e56#diff-3f9a3ce4da7091038e7c311b59edcfb4a38e0fe8015590d79d345dd1d5aabfacL18

A newer version of imgbased is required. But this causes issues when upgrading from 4.4.X versions.

**To reproduce**
Have a ovirt-node running 4.4.10 for example. And then upgrade it:
Error: 
 Problem: package ovirt-node-ng-image-update-4.5.0.2-1.el8.noarch requires imgbased >= 1.2.24, but none of the providers can be installed
  - cannot install the best update candidate for package ovirt-node-ng-image-update-4.4.10.2-1.el8.noarch
  - package imgbased-1.2.24-1.el8.noarch is filtered out by exclude filtering

**Expected behavior**
The imgbased version is already in the update package, so no need for a dependency so upgrade works fine? :)

**Comment by sandrobonazzola** [comment]
fixed by #53 preparing a respin.
